make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C /home/vagrant/RIOT/tests/gnrc_sock_dns test

Traceback (most recent call last):
  File "/home/vagrant/RIOT/tests/gnrc_sock_dns/tests/01-run.py", line 318, in <module>
    sys.exit(run(testfunc, timeout=1, echo=False))
  File "/home/vagrant/RIOT/dist/pythonlibs/testrunner/__init__.py", line 30, in run
    testfunc(child)
  File "/home/vagrant/RIOT/tests/gnrc_sock_dns/tests/01-run.py", line 275, in testfunc
    tap = get_bridge(os.environ["TAP"])
  File "/home/vagrant/RIOT/tests/gnrc_sock_dns/tests/01-run.py", line 108, in get_bridge
    "master"
  File "/home/vagrant/RIOT/tests/gnrc_sock_dns/tests/01-run.py", line 96, in check_and_search_output
    output = subprocess.check_output(cmd, *args, **kwargs).decode("utf-8")
  File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bridge': 'bridge'
make: *** [/home/vagrant/RIOT/tests/gnrc_sock_dns/../../Makefile.include:770: test] Error 1

Return value: 2
